[project]
name = "ytmidilib"
dynamic = ["version"]
description = "MIDI library"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Yoichi Tanibayashi", email = "yoichi@tanibayashi.jp" }
]
requires-python = ">=3.13"
dependencies = [
  "click",
  "mido",
  "pygame-ce",
  "numpy",
  "loguru>=0.7.3",
]

[project.scripts]
ytmidilib = "ytmidilib.__main__:cli"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[dependency-groups]
dev = [
    "basedpyright>=1.37.3",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.14",
]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "B", "UP"]

[tool.mypy]
python_version = "3.13"
check_untyped_defs = true

[[tool.mypy.overrides]]
module = "click,loguru,loguru.*,pytest,pytest.*,blessed,blessed.*,mido,mido.*"
ignore_missing_imports = true
follow_untyped_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v --cov=ytmidilib --cov-report=term-missing --cov-branch"

[tool.basedpyright]
include = ["src", "tests"]
typeCheckingMode = "standard"
reportMissingSuperCall = false
reportPossiblyUnboundVariable = "none"
reportMissingImports = "none"
reportOptionalCall = "none"
reportUnknownVariableType = "none"
reportUnknownArgumentType = "none"
reportDuplicateImport = "warning"
reportUnreachable = "warning"
reportDeprecated = "warning"
useLibraryCodeForTypes = true
